project_id = "zebifcfhjnglycwfgraq"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.create-blog-post]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.upload-blog-image]
    verify_jwt = false
